### ISSUE TITLE
Short Profile Page UI Implementation

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/AppDevelopmentCollection#1]
Create a short UI Page Implementation, that can help people understand

**Comment by vedant130701** [comment]
I would like to contribute to this!

**Comment by codetravellearn** [comment]
i would like to contribute

**Comment by onosyoono** [comment]
I'm sorry @codetravellearn but @vedant130701 asked first, if they are unable to finish it. You can definitely try, also try looking at other issues in this repository. We will be having a list of them. Also, if you feel you can contribute something interesting, not present we would gladly accept.
