### ISSUE TITLE
Mobile App Calculator

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/AppDevelopmentCollection#4]
Create an app for a simple calculator, which can act as base for beginners.

**Comment by Bhavna777** [comment]
I want to work on it.

**Comment by onosyoono** [comment]
Sure, you are welcome to contribute

**Comment by alijatoi** [comment]
I want to Work On it . which language is needed to do ?

**Comment by onosyoono** [comment]
Any language, which is comfortable, however, implementation of the same project in different languages are also welcome. It would be better if @Bhavna777 and you (@alijatoi ) can come to common decision to work on it using different languages.

**Comment by alijatoi** [comment]
Ok I will be working it on with C++..

**Comment by alijatoi** [comment]
You Changed the name. please elaborate the project details so that i can start

**Comment by onosyoono** [comment]
The implementation is supposed to be for phone application, like using Flutter, Kotlin and Java.

**Comment by MARCOSM-MARTINS** [comment]
Hello, I'm a Flutter developer. I can also make a contribution using Dart.
Can I start?

**Comment by marcos1martins** [comment]
Hello, I'm a Flutter developer. I can also make a contribution using Dart.
Can I start?
